apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcriber
  labels:
    app: transcriber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transcriber
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
  template:
    metadata:
      labels:
        app: transcriber
    spec:
      containers:
        - name: transcriber
          image: manuelnongba/transcriber
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
          resources:
            requests:
              memory: '1Gi'
              cpu: '500m'
            limits:
              memory: '2Gi'
              cpu: '1000m'
