apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcriber
  labels:
    app: transcriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcriber
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
  template:
    metadata:
      labels:
        app: transcriber
    spec:
      containers:
        - name: transcriber
          image: manuelnongba/transcriber
          ports:
            - containerPort: 8080
