apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator
  labels:
    app: translator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: translator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
  template:
    metadata:
      labels:
        app: translator
    spec:
      containers:
        - name: translator
          image: manuelnongba/translator
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
          resources:
            requests:
              memory: '1Gi'
              cpu: '500m'
            limits:
              memory: '2Gi'
              cpu: '1000m'
