apiVersion: v1
kind: Service
metadata:
  name: translator-service
  labels:
    app: translator
spec:
  selector:
    app: translator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
